# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorBookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='visitorsbook/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
