# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsbook', '0002_auto_20161122_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorbookmessage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
