# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsbook', '0003_auto_20161122_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorbookmessage',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
