# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsbook', '0005_auto_20161122_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorbookmessage',
            options={'ordering': ('-date',)},
        ),
    ]
