# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.FileField(null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
