# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
