# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161116_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ('order',)},
        ),
    ]
