# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161116_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
