# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170112_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=50)),
                ('phone', models.CharField(blank=True, default=None, max_length=15)),
            ],
        ),
    ]
