# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
