# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscriber_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AddField(
            model_name='post',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
