"""
Django settings for buscandolaidea project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u@b-286maima8w*8fz)ue+kov8a%#+w35ap44&4ox(dwe6_oqy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'buscandolaidea.apps.BuscandolaideaConfig',
    'blog.apps.BlogConfig',
    'contact.apps.ContactConfig',
    'visitorsbook.apps.VisitorsbookConfig',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'buscandolaidea.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'buscandolaidea.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'buscandolaidea',
        'USER': 'xxxxx',
        'PASSWORD': 'xxxxxx',
        'HOST': 'xxxxxx',
        'PORT': 'xxxxxx',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# Absolute filesystem path to the directory that will hold all the static files. Production server will serve these
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Relative path that handles the media served from STATIC_ROOT
STATIC_URL = '/static/'

# Absolute filesystem path to the directory that will hold user uploaded files.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Relative path that handles the media served from MEDIA_ROOT
MEDIA_URL = '/media/'

# NOT FOR PRODUCTION - Instead of sending an email, prints it in the stdout
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production, specify EMAIL_HOST  and EMAIL_PORT (https://docs.djangoproject.com/en/1.10/topics/email/#module-django.core.mail)

# Blog settings
BLOG_IMAGES_STORAGE_DIRECTORY = 'blog/%Y/%m/%d/'
BLOG_LOAD_JQUERY = False
BLOG_THUMBNAIL_SMALL = (80, 45)
BLOG_THUMBNAIL_MEDIUM = (300, 250)
BLOG_THUMBNAIL_BIG = (800, 600)

# Vistor's book settings
VISITORS_BOOK_IMAGES_STORAGE_DIRECTORY = 'visitorsbook/%Y/%m/%d/'
VISITORS_BOOK_MESSAGE_IMAGE_SIZE = (300, 250)



























